# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'URDdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 322)
        Dialog.setModal(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 700, 320))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 55, 30))
        self.label.setObjectName("label")
        self.GS = QtWidgets.QComboBox(self.groupBox)
        self.GS.setGeometry(QtCore.QRect(10, 50, 50, 30))
        self.GS.setObjectName("GS")
        self.GS.addItem("")
        self.GS.addItem("")
        self.GS_2 = QtWidgets.QComboBox(self.groupBox)
        self.GS_2.setGeometry(QtCore.QRect(10, 90, 50, 30))
        self.GS_2.setObjectName("GS_2")
        self.GS_2.addItem("")
        self.GS_2.addItem("")
        self.GS_3 = QtWidgets.QComboBox(self.groupBox)
        self.GS_3.setGeometry(QtCore.QRect(10, 130, 50, 30))
        self.GS_3.setObjectName("GS_3")
        self.GS_3.addItem("")
        self.GS_3.addItem("")
        self.GS_4 = QtWidgets.QComboBox(self.groupBox)
        self.GS_4.setGeometry(QtCore.QRect(10, 170, 50, 30))
        self.GS_4.setObjectName("GS_4")
        self.GS_4.addItem("")
        self.GS_4.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 120, 30))
        self.label_2.setObjectName("label_2")
        self.URD_itemname = QtWidgets.QLineEdit(self.groupBox)
        self.URD_itemname.setGeometry(QtCore.QRect(80, 50, 140, 30))
        self.URD_itemname.setObjectName("URD_itemname")
        self.URD_itemname_2 = QtWidgets.QLineEdit(self.groupBox)
        self.URD_itemname_2.setGeometry(QtCore.QRect(80, 90, 140, 30))
        self.URD_itemname_2.setObjectName("URD_itemname_2")
        self.URD_itemname_3 = QtWidgets.QLineEdit(self.groupBox)
        self.URD_itemname_3.setGeometry(QtCore.QRect(80, 130, 140, 30))
        self.URD_itemname_3.setObjectName("URD_itemname_3")
        self.URD_itemname_4 = QtWidgets.QLineEdit(self.groupBox)
        self.URD_itemname_4.setGeometry(QtCore.QRect(80, 170, 140, 30))
        self.URD_itemname_4.setObjectName("URD_itemname_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(230, 10, 70, 30))
        self.label_3.setObjectName("label_3")
        self.URD_gtwt = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_gtwt.setGeometry(QtCore.QRect(240, 50, 130, 30))
        self.URD_gtwt.setDecimals(3)
        self.URD_gtwt.setMaximum(999.999)
        self.URD_gtwt.setObjectName("URD_gtwt")
        self.URD_gtwt_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_gtwt_2.setGeometry(QtCore.QRect(240, 90, 130, 30))
        self.URD_gtwt_2.setDecimals(3)
        self.URD_gtwt_2.setMaximum(999.999)
        self.URD_gtwt_2.setObjectName("URD_gtwt_2")
        self.URD_gtwt_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_gtwt_3.setGeometry(QtCore.QRect(240, 130, 130, 30))
        self.URD_gtwt_3.setDecimals(3)
        self.URD_gtwt_3.setMaximum(999.999)
        self.URD_gtwt_3.setObjectName("URD_gtwt_3")
        self.URD_gtwt_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_gtwt_4.setGeometry(QtCore.QRect(240, 170, 130, 30))
        self.URD_gtwt_4.setDecimals(3)
        self.URD_gtwt_4.setMaximum(999.999)
        self.URD_gtwt_4.setObjectName("URD_gtwt_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(390, 10, 80, 30))
        self.label_4.setObjectName("label_4")
        self.URD_ntwt = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_ntwt.setGeometry(QtCore.QRect(390, 50, 130, 30))
        self.URD_ntwt.setDecimals(3)
        self.URD_ntwt.setMaximum(999.999)
        self.URD_ntwt.setObjectName("URD_ntwt")
        self.URD_ntwt_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_ntwt_2.setGeometry(QtCore.QRect(390, 90, 130, 30))
        self.URD_ntwt_2.setDecimals(3)
        self.URD_ntwt_2.setMaximum(999.999)
        self.URD_ntwt_2.setObjectName("URD_ntwt_2")
        self.URD_ntwt_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_ntwt_3.setGeometry(QtCore.QRect(390, 130, 130, 30))
        self.URD_ntwt_3.setDecimals(3)
        self.URD_ntwt_3.setMaximum(999.999)
        self.URD_ntwt_3.setObjectName("URD_ntwt_3")
        self.URD_ntwt_4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.URD_ntwt_4.setGeometry(QtCore.QRect(390, 170, 130, 30))
        self.URD_ntwt_4.setDecimals(3)
        self.URD_ntwt_4.setMaximum(999.999)
        self.URD_ntwt_4.setObjectName("URD_ntwt_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(540, 10, 110, 30))
        self.label_5.setObjectName("label_5")
        self.URD_amount = QtWidgets.QSpinBox(self.groupBox)
        self.URD_amount.setGeometry(QtCore.QRect(540, 50, 140, 30))
        self.URD_amount.setMaximum(9999999)
        self.URD_amount.setObjectName("URD_amount")
        self.URD_amount_2 = QtWidgets.QSpinBox(self.groupBox)
        self.URD_amount_2.setGeometry(QtCore.QRect(540, 90, 140, 30))
        self.URD_amount_2.setMaximum(9999999)
        self.URD_amount_2.setObjectName("URD_amount_2")
        self.URD_amount_3 = QtWidgets.QSpinBox(self.groupBox)
        self.URD_amount_3.setGeometry(QtCore.QRect(540, 130, 140, 30))
        self.URD_amount_3.setMaximum(9999999)
        self.URD_amount_3.setObjectName("URD_amount_3")
        self.URD_amount_4 = QtWidgets.QSpinBox(self.groupBox)
        self.URD_amount_4.setGeometry(QtCore.QRect(540, 170, 140, 30))
        self.URD_amount_4.setMaximum(9999999)
        self.URD_amount_4.setObjectName("URD_amount_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(350, 210, 190, 30))
        self.label_6.setObjectName("label_6")
        self.URD_total = QtWidgets.QSpinBox(self.groupBox)
        self.URD_total.setGeometry(QtCore.QRect(540, 210, 140, 30))
        self.URD_total.setMaximum(9999999)
        self.URD_total.setObjectName("URD_total")
        self.Submit = QtWidgets.QPushButton(self.groupBox)
        self.Submit.setGeometry(QtCore.QRect(380, 270, 140, 40))
        self.Submit.setObjectName("Submit")
        self.Cancel = QtWidgets.QPushButton(self.groupBox)
        self.Cancel.setGeometry(QtCore.QRect(540, 270, 140, 40))
        self.Cancel.setObjectName("Cancel")
        self.exit=QtWidgets.QWidget()

        self.URDpass=[]
        self.URD_list={}
        self.URD_gtwt.valueChanged.connect(lambda: self.URD_ntwt.setValue(self.URD_gtwt.value()))
        self.URD_gtwt_2.valueChanged.connect(lambda: self.URD_ntwt_2.setValue(self.URD_gtwt_2.value()))
        self.URD_gtwt_3.valueChanged.connect(lambda: self.URD_ntwt_3.setValue(self.URD_gtwt_3.value()))
        self.URD_gtwt_4.valueChanged.connect(lambda: self.URD_ntwt_4.setValue(self.URD_gtwt_4.value()))
        self.URD_amount.valueChanged.connect(lambda: self.total_amount())
        self.URD_amount_2.valueChanged.connect(lambda: self.total_amount())
        self.URD_amount_3.valueChanged.connect(lambda: self.total_amount())
        self.URD_amount_4.valueChanged.connect(lambda: self.total_amount())
        self.Cancel.clicked.connect(lambda: Dialog.reject())

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def total_amount(self):
        total=self.URD_amount.value()+self.URD_amount_2.value()+self.URD_amount_3.value()+self.URD_amount_4.value()
        self.URD_total.setValue(total)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "G/S"))
        self.GS.setItemText(0, _translate("Dialog", "G"))
        self.GS.setItemText(1, _translate("Dialog", "S"))
        self.GS_2.setItemText(0, _translate("Dialog", "G"))
        self.GS_2.setItemText(1, _translate("Dialog", "S"))
        self.GS_3.setItemText(0, _translate("Dialog", "G"))
        self.GS_3.setItemText(1, _translate("Dialog", "S"))
        self.GS_4.setItemText(0, _translate("Dialog", "G"))
        self.GS_4.setItemText(1, _translate("Dialog", "S"))
        self.label_2.setText(_translate("Dialog", "URD Item"))
        self.label_3.setText(_translate("Dialog", "Gr Wt"))
        self.label_4.setText(_translate("Dialog", "Nt Wt"))
        self.label_5.setText(_translate("Dialog", "Amount"))
        self.label_6.setText(_translate("Dialog", "Total Amount:"))
        self.Submit.setText(_translate("Dialog", "Submit"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))

    def connect_dialog(self, Dialog):
        if self.URD_itemname.text()!=''and self.URD_gtwt.value()!=0.0 and self.URD_ntwt.value()!=0.0 and self.URD_amount.value()!=0:
            self.URD_list['1']=[self.GS.currentText(), self.URD_itemname.text(), self.URD_gtwt.value(), self.URD_ntwt.value(), self.URD_amount.value()]
        if self.URD_itemname_2.text()!=''and self.URD_gtwt_2.value()!=0.0 and self.URD_ntwt_2.value()!=0.0 and self.URD_amount_2.value()!=0:
            self.URD_list['2']=[self.GS_2.currentText(), self.URD_itemname_2.text(), self.URD_gtwt_2.value(), self.URD_ntwt_2.value(), self.URD_amount_2.value()]
        if self.URD_itemname_3.text()!=''and self.URD_gtwt_3.value()!=0.0 and self.URD_ntwt_3.value()!=0.0 and self.URD_amount_3.value()!=0:
            self.URD_list['3']=[self.GS_3.currentText(), self.URD_itemname_3.text(), self.URD_gtwt_3.value(), self.URD_ntwt_3.value(), self.URD_amount_3.value()]
        if self.URD_itemname_4.text()!=''and self.URD_gtwt_4.value()!=0.0 and self.URD_ntwt_4.value()!=0.0 and self.URD_amount_4.value()!=0:
            self.URD_list['4']=[self.GS_4.currentText(), self.URD_itemname_4.text(), self.URD_gtwt_4.value(), self.URD_ntwt_4.value(), self.URD_amount_4.value()]

        temp_itemname=''
        temp_goldgrwt=0.000
        temp_goldntwt=0.000
        temp_silvergrwt=0.000
        temp_silverntwt=0.000
        for key in self.URD_list.keys():
            temp_itemname=', '.join([temp_itemname ,self.URD_list[key][1]])
            if self.URD_list[key][0]=='G':
                temp_goldgrwt+=self.URD_list[key][2]
                temp_goldntwt+=self.URD_list[key][3]
            if self.URD_list[key][0]=='S':
                temp_silvergrwt+=self.URD_list[key][2]
                temp_silverntwt+=self.URD_list[key][3]
        temp_itemname=temp_itemname[2:]
        self.URDpass=[self.URD_total.value(), temp_itemname, temp_goldgrwt, temp_goldntwt, temp_silvergrwt, temp_silverntwt]
        del self.URD_list
        print(self.URDpass)
        Dialog.accept()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
